config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'user#index'
  
  resources :games
  resources :user
  resources :rps
  resources :c4games
  resources :advgames
  resources :minesweepers
  resources :mmgames

end

app/models/game.rb
class Game < ActiveRecord::Base
#game methods go here
# validate :move_is_in_correct_range
# validates :move, :inclusion => 0..8
validates :p1_id, presence: true
validates :p2_id, presence: true
# validates_inclusion_of :move, :in => 0..8
has_and_belongs_to_many :users


WINNING_LINES = [ [0,1,2], [3,4,5], [6,7,8], [0,3,6], [1,4,7], [2,5,8], [0,4,8], [2,4,6] ]
  #check if current_board is empty and initialize if so
  def current_board
    @current_board
  end

  def winning_pieces(piece)
    if find_winning_pieces != nil
      true if find_winning_pieces.flatten.include? piece
    end

  end

  def check_current_board
    if self.moves == nil
      @current_board = [0, 0, 0, 0, 0, 0, 0, 0, 0]
    else
      @current_board = self.board.split(' ')
    end
  end

  def board_test
    @current_board[2] = 1
  end
  #if moves count is odd, p1, else p2
  def check_player
    if self.moves == nil or self.moves.length % 2 == 0
      @current_player = 1
    else
      @current_player = 2
    end  
  end

  def makemovetest(sq)
    @current_board[sq] = @current_player
    self.board = @current_board.join
  end

  def winlines
    WINNING_LINES
  end

  def game_won
    !!WINNING_LINES.detect do |winning_line|
      %w(111 222).include?(winning_line.map { |e| self.board.split(' ')[e] }.join)
    end
  end

  def determine_winner
    if self.moves.length % 2 == 0
      2
    else
      1
    end
  end

  def return_winner
    if self.winner == 1
      User.find(self.p1_id)
    else
      User.find(self.p2_id)
    end
  end

  def game_drawn
    return false if self.moves == nil
    return true if self.moves.length >= 9
  end

  def computers_shot
    self.check_player == 2 && self.users.last.human == false
  end

  def computer_turn

    if (self.check_player == 2 && User.find(p2_id).human == false)# || (self.check_player == 1 && self.users.first.human == false)
      case User.find(p2_id).computer_type
      when 'random'
        move = rand(8)
        if self.moves != nil
          until self.moves.exclude? move.to_s
           move=rand(8)     
         end
       end
       return move
     when 'level1'
      l1_computer_logic
      when 'level2'
      l2_computer_logic
      when 'level3'
      l3_computer_logic
    end
  end
end

def find_winning_pieces
  @testmoves = []
  if board != nil
  WINNING_LINES.each_with_index do |line, ind|
    b = board.split
      if (b[line[0]] == "1") && (b[line[1]] == "1") && (b[line[2]] == "1")
        @testmoves << line
      end
      if (b[line[0]] == "2") && (b[line[1]] == "2") && (b[line[2]] == "2")
        @testmoves << line
      end
  end
  return @testmoves
  end

end


private

def move_is_in_correct_range
   # errors.add(:move, "should be less than 8") if :move<=8
   binding.pry;
 end

 def l1_computer_logic
   if self.moves.length == 1
     if self.moves == "4"
       move = 0
     else
       move = 4
     end
   else
     lastmove = self.moves[-2, 1].to_i
     # if self.moves.include? lastmove+1
     move = lastmove+1
     # binding.pry;''    
     if self.moves.include? move.to_s || (move == 9)
      move = lastmove-1
    end
     # binding.pry;''
     if self.moves.include? move.to_s || (move == -1)
      until self.moves.exclude? move.to_s
       move=rand(8) 
     end
   end
   return move
 end
end

def l2_computer_logic
  @remaining_moves = [0,1,2,3,4,5,6,7,8]
  @p1_moves = []
  @p2_moves = []
  self.moves.split(//).each_with_index do |move, index|
    @remaining_moves.delete_at(move.to_i)
    if index % 2 == 0
      @p1_moves << move
    else
      @p2_moves << move
    end
  end
  @testmoves = []
  WINNING_LINES.each_with_index do |line, ind|
    b = board.split
    3.times do
      if (b[line[0]] == b[line[1]])
        @testmoves << line[2]
      end
      line.rotate!
    end
  end

  if @testmoves.length >= 1
    moveslist = @testmoves.group_by(&:itself).values.max_by(&:size)
    moveslist = (moveslist << @remaining_moves).flatten
    move = moveslist[0]
    i=0
    until self.moves.exclude? move.to_s
      i = (i+1)
      move = moveslist[i]
      break if i==moveslist.length
    end 
else
  move=l1_computer_logic
end
return move
end

# def check_for_pairs
#   !!WINNING_LINES.detect do |winning_line|
#     %w(111 222).include?(winning_line.map { |e| self.fakeboard.split(' ')[e] }.join)
#   end
# end

def l3_computer_logic
  @remaining_moves = [0,1,2,3,4,5,6,7,8]
  @p1_moves = []
  @p2_moves = []
  self.moves.split(//).each_with_index do |move, index|
    @remaining_moves.delete_at(move.to_i)
    if index % 2 == 0
      @p1_moves << move
    else
      @p2_moves << move
    end
  end



  @testmoves = []
  WINNING_LINES.each_with_index do |line, ind|
    b = board.split
    3.times do
      if (b[line[0]] == "1") && (b[line[1]] == "1") && (b[line[2]] == "0")
        @testmoves << line[2]
      end
      line.rotate!
    end
  end

  if @testmoves.length >= 1
    moveslist = @testmoves.group_by(&:itself).values.max_by(&:size)
    moveslist = (moveslist << @remaining_moves).flatten
    move = moveslist[0]
    i=0
    until self.moves.exclude? move.to_s
      i = (i+1)
      move = moveslist[i]
      break if i==moveslist.length
    end 
else
  move=l1_computer_logic
end
return move
end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @games = Game.all.order(updated_at: :desc)
  end

  def new
    @game = Game.new
  end

  def create
    gid = Game.create(game_params).id
    add_users(gid)
    redirect_to(edit_game_path(gid))
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    params['move'] = params['game']['move']
    @game = Game.find(params[:id])


    if check_move
      add_move(params[:move].to_i)
    else
      error = "Illegal Move"
    end
    @game.update(game_params)
    if @game.game_won
      winner = @game.determine_winner
      @game.winner = winner
      @game.save
      @game.return_winner.add_win_to_player
      redirect_to(@game)
    elsif @game.game_drawn
      User.find(@game.p1_id).add_draw_to_player
      User.find(@game.p2_id).add_draw_to_player
      redirect_to(@game)
    else
      # computer_move
      if @game.computer_turn != nil 
        if !(@game.game_won || @game.game_drawn)
          add_move(@game.computer_turn.to_i)
          @game.update(game_params)
          if @game.game_won
            winner = @game.determine_winner
            @game.winner = winner
            @game.save
            @game.return_winner.add_win_to_player
          end
        end
      end
      flash[:notice] = error
      redirect_to(edit_game_path(@game.id))
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  private
  def game_params
    params.require(:game).permit(:moves, :board, :p1_id, :p2_id)
  end

  def add_users(id)
    newgame = Game.find(id)
    newgame.users << User.find(newgame.p1_id)
    newgame.users << User.find(newgame.p2_id)
  end 

  def check_move
    # move = params['game']['move'].to_i
    move = params[:move].to_i
    board = params['game']['board'].split
    if board[move].to_i == 0
      return true
    else
      return false
    end
  end

  def add_move(move)
    current_space = params['game']['board'].split
    current_player = @game.check_player
    board = params['game']['board'].split
    board[move] = current_player
    params['game']['board'] = board.join(' ')
    if @game.moves == nil
      @game.moves = move
    else
      @game.moves += move.to_s
    end
  end
end

app/views/games/_selectuserslist.html.erb
<%= form_for @game do |f| %>
  <%= f.hidden_field :p1_id, :value => current_user.id %>
  <%= f.label :p2_id %>
  <%= f.collection_select :p2_id, User.where.not(id: current_user.id).order(:email),:id,:email, :selected => params['p2_id'] %>
  <br>
  <%= f.submit 'Create Game' %>
  <% end %>

app/views/games/_viewboard.html.erb
<div class="board">
  <% @game.current_board.each_with_index do |square, i| %>
  <% @wp = [] %>
  <% @wp = @game.find_winning_pieces if (@game.moves!=nil && @game.game_won) %>
    <div class="boardsquare" id="sq<%= i %>">
    
      <% case square.to_i when 0 %> <%#= radio_button_tag :move, i %> 
        <%= form_for @game do |f| %>
          <%= f.hidden_field :p1_id, :value => @game.p1_id %>
          <%= f.hidden_field :p2_id, :value => @game.p2_id %>
          <%= f.hidden_field :board, :value => @game.current_board %>
          <%= f.hidden_field :move, :value => i %>
          <%= f.submit '', :class => 'blank_button' unless (@game.moves != nil && @game.game_won == true)%>
        <% end %>
      <% when 1 %><div <%= "class=blink_me" if @game.winning_pieces(i)%>><p class='naught'><%= image_tag('o.png') %></p></div>
      <% when 2 %><div <%= "class=blink_me" if @game.winning_pieces(i)%>><p class='cross'><%= image_tag('x.png') %></p></div>
      <% else %>Err  
      <% end %>
    </div>
  <% end %>
</div>
<%#=(link_to 'a', {controller: 'games', action: 'update', p1_id: @game.p1_id, move: i, p2_id: @game.p2_id, board: @game.board}, method: :put)%>

app/views/games/edit.html.erb
<% @game.check_current_board %>
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>
<strong><%=@game.users.first.email %></strong> vs <strong><%= @game.users.last.email %></strong>
<% if @game.winner != nil %>
  <h2>The winner is..... <%= @game.return_winner.email %>

<% else %>
  <h2>Turn: <%= @game.check_player %></h2>
<% end %>
<%= render partial: 'viewboard' %>
<% `say "Lets play Tic Tac Toe!"` if @game.moves == nil  %>
<% `open ~/mk.mp3 & ` if @game.moves == nil  %>

app/views/games/index.html.erb
<table>
  <tr>
    <th>Game Number</th>
    <th>Player 1</th>
    <th>Player 2</th>
    <th>Play</th>
    <th>Winner</th>
  </tr>
  
<% @games.each do |game| %>

<tr>
<td><%=link_to("Game #{game.id}", game_path(game.id))%></td>
<td><%=link_to(User.find(game.p1_id).email, user_path(game.p1_id))%></td>
<td><%=link_to(User.find(game.p2_id).email, user_path(game.p2_id))%></td>
<td><% if game.moves == nil || (game.game_drawn == nil && game.winner==nil) %>
<%= link_to('Play', edit_game_path(game)) if can? :edit, Game  %>
<% else %>
<strong>Game Finished</strong>
<% end %></td>
<td><%= User.find(game.p1_id).email if game.winner==1 %>
<%= User.find(game.p2_id).email if game.winner==2 %>
<%= "Draw" if game.moves != nil && game.game_drawn %></td>
</tr>
<% end %>
</table>

app/views/games/new.html.erb
<% if user_signed_in? %>
<%= render partial: 'selectuserslist' %>
<% else %>
<p>You must be signed in to issue a challenge</p>
<% end %>

app/views/games/show.html.erb
<% `killall iTunes` %>
<% @game.check_current_board %>
  <strong><%=@game.users.first.email %></strong> vs <strong><%= @game.users.last.email %></strong>
  <% if @game.game_won %>
    <h1 class="blink_me">Game Won!</h2>
    <%= @game.return_winner.email %>
    <% `say "#{@game.return_winner.email} ... wins"` %>
  <% elsif @game.game_drawn %>
    <h1 class="blink_me">Its a DRAW!!!</h2>
    <% `say "Double K O!"` %>
  <% end %>

  <%= render partial: 'viewboard' %>

  <%= link_to "Rematch!", "/games/new?p1_id=#{@game.p1_id}&p2_id=#{@game.p2_id}" %>

  <%= link_to('Show All', games_path) %>
 
  