config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'user#index'
  
  resources :games
  resources :user
  resources :rps
  resources :c4games
  resources :advgames
  resources :minesweepers
  resources :mmgames

end

app/models/rp.rb
class Rp < ActiveRecord::Base
  has_and_belongs_to_many :users

  def determine_winner(p1, p2)
    case [p1.to_i, p2.to_i]
    when [1, 1]
      0
    when [2, 2]
      0
    when [3, 3]
      0
    when [1, 2]
      1
    when [1, 3]
      2
    when [2, 1]
      2
    when [2, 3]
      2
    when [3, 1]
      1
    when [3, 2]
      2
    else 
      0
    end
  end

  def winning_message(p1, p2)
    case [p1.to_i, p2.to_i]
    when [1, 1]
      'Rock Kills Rock'
    when [2, 2]
      'Paper Wipes Paper'
    when [3, 3]
      'Scissors Eat Scissors'
    when [1, 2]
      'Paper Wraps Rock'
    when [1, 3]
      'Rock Breaks Scissors'
    when [2, 1]
      'Paper Wraps Rock'
    when [2, 3]
      'Scissors Cut Paper'
    when [3, 1]
      'Rock Breaks Scissors'
    when [3, 2]
      'Scissors Cut Paper'
    else 
      'Error'
    end
  end

  end

app/controllers/rps_controller.rb
class RpsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @rps = Rp.all.order(updated_at: :desc)
  end

  def new
    @game = Rp.new
  end

  def create
    gid = Rp.create(rp_params).id
    add_users(gid)
    redirect_to(edit_rp_path(gid))
  end

  def edit
    @rp = Rp.find(params[:id])
  end

  def update
    @rp = Rp.find(params[:id])
    # binding.pry;''
    winner = @rp.determine_winner(params[:rp][:p1_move], params[:rp][:p2_move])
    set_winner_id(winner)
    @rp.update(rp_params)
    if @rp.winner_id == nil
      User.find(@rp.p1_id).add_draw_to_player
      User.find(@rp.p2_id).add_draw_to_player
    else
      User.find(@rp.winner_id).add_win_to_player 
    end 
    @rp.save
    redirect_to(@rp)
  end

  def show
    @rp = Rp.find(params[:id])
  end

private
  def rp_params
    params.require(:rp).permit(:winner_id, :p1_id, :p2_id, :p1_move, :p2_move)
    end

    def add_users(id)
      newgame = Rp.find(id)
      newgame.users << User.find(newgame.p1_id)
      newgame.users << User.find(newgame.p2_id)
    end 

    def set_winner_id(winner)
      if winner == 1
        @rp.winner_id = @rp.p1_id
      elsif winner == 2
        @rp.winner_id = @rp.p1_id
      end
    end
end

app/helpers/rps_helper.rb
module RpsHelper
end

app/views/rps/edit.html.erb
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<strong><%=User.find(@rp.p1_id).email %></strong> vs <strong><%= User.find(@rp.p2_id).email %></strong>

<% if @rp.winner_id != nil %>
<h2>The winner is..... <%= User.find(@rp.winner_id).email %>
<% else %>

  <%= form_for @rp do |f| %>
  <%= f.hidden_field :p1_id, :value => @rp.p1_id %>
  <%= f.hidden_field :p2_id, :value => @rp.p2_id %>
  <%= select_tag('rp[p1_move]', options_for_select([['Rock', 1], ['Paper', 2], ['Scissors', 3]])) %>
  <% if User.find(@rp.p2_id).human == true %>
  <%= select_tag('rp[p2_move]', options_for_select([['Rock', 1], ['Paper', 2], ['Scissors', 3]])) %>
  <% else %>
  <%= f.hidden_field :p2_move, :value => (rand(1..3)) %>
  <% end %>
  <%= f.submit %>
  <% end %>
<% end %>

app/views/rps/index.html.erb
<h2>Rock Paper Scissors</h2>

<table>
  <tr>
    <th>Game No</th>
    <th>Player 1</th>
    <th>Player 2</th>
    <th>Winner</th>
    <th>Play</th>
  </tr>
  <% @rps.each do |game| %>
  <tr>
    <td><%= link_to(game.id, rp_path(game.id)) %></td>
    <td><%= game.users.first.email %></td>
    <td><%= game.users.last.email %></td>
    <td><%= User.find(game.winner_id).email if game.winner_id != nil %></td>
    <td><%= link_to("Play", edit_rp_path(game)) if (game.p1_move && game.p2_move)==nil %></td>
  </tr>
<% end %>

</table>

app/views/rps/show.html.erb
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>
<strong><%=User.find(@rp.p1_id).email %></strong> vs <strong><%= User.find(@rp.p2_id).email %></strong>
<% if @rp.winner_id != nil %>
<h2>The winner is..... <%= User.find(@rp.winner_id).email %></h2>
<% end %>
<br>

<%= link_to "Rematch!", "/rps/new?p1_id=#{@rp.p1_id}&p2_id=#{@rp.p2_id}" %>
<%= link_to "Show All", rps_path %>

<h1>
<%=@rp.winning_message(@rp.p1_move, @rp.p2_move)%></h1>

<div class="rpsimage">
<% case @rp.p1_move %>
<% when 1 %>
<%= image_tag('rock.png', size: "200x200") %>
<% when 2 %>
<%= image_tag('paper.svg', size: "200x200") %>
<% when 3 %>
<%= image_tag('scissors.png', size: "200x200") %>
<% end %>
</div>
<div class="rpsimage">

<% case @rp.p2_move %>
<% when 1 %>
<%= image_tag('rock.png', size: "200x200") %>
<% when 2 %>
<%= image_tag('paper.svg', size: "200x200") %>
<% when 3 %>
<%= image_tag('scissors.png', size: "200x200") %>
<% end %>
</div>