config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'user#index'
  
  resources :games
  resources :user
  resources :rps
  resources :c4games
  resources :advgames
  resources :minesweepers
  resources :mmgames

end

app/views/layouts/_head.html.erb
<div class="head">
  <h1>Gamification</h1>
  <div class="navbar">
  <nav>
    <ul class="menu">
      <% if user_signed_in? %>
      <li><%= link_to('Log out', destroy_user_session_path, :method => :delete ) %></li>
      <li><%= link_to('User Page', user_path(current_user.id)) %></li>
      <% else %>
      <li><%= link_to('Log in', new_user_session_path) %> </li>
    </li>
    <li><%= link_to('Register', new_user_registration_path) %></li>
    <% end %>
    <li><%= link_to('League Table', '/') %></li></ul>
    <ul class="menu">
      <li><%= link_to('New TicTacToe', new_game_path) %></li>
      <li><%= link_to('Show all TTT Matches', games_path) %></li></ul>
      <ul class="menu">
        <li><%= link_to('New Rock Paper Scissors', new_rp_path) %></li>
        <li><%= link_to('Show all RPS''s', rps_path) %></li></ul>
        <ul class="menu">
          <li><%= link_to('New Connect Four', new_c4game_path) %></li>
          <li><%= link_to('All Connect Four Games', c4games_path) %></li></ul>
        </ul>
        <ul class="menu"><li><%= link_to('New ADVANCED TicTacToe', new_advgame_path) %></li>
        <li><%= link_to('All Advanced TicTacToe Games', advgames_path) %></li></ul>
        <ul class="menu">
          <li><%= link_to('New Mastermind', new_mmgame_path) %></li>
          <li><%= link_to('All Mastermind Games', mmgames_path) %></li></ul>
        </ul>
</nav></div>
<div class='headerinfo'>
<% if user_signed_in? %>
<ul><li>Signed in as: <%= current_user.email %></li>
  <li>Role: <%= current_user.role %></li>
  <li>Total Points: <%= current_user.points %></li></ul>
  <% end %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamification</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/head' %>
  <div class="main">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
</div>
<div class="footer">
</div>
  </body>
  </html>